import "@/css/satoshi.css";
import "@/css/style.css";
import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { PropsWithChildren } from "react";
import { Providers } from "./providers";
import NextTopLoader from "nextjs-toploader";
import { getUserFromCookie } from "@/actions/auth/getUserFromCookie.action";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Anderson Almeyda | Full-Stack Developer",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }: PropsWithChildren) {
	const user = await getUserFromCookie();
	return (
		<html lang="es" suppressHydrationWarning>
			<body
				id="__almeyda"
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Providers user={user}>
					<NextTopLoader color="#5750F1" showSpinner={false} />
					{children}
				</Providers>
			</body>
		</html>
	);
}
